const { buildResponseLanguageInstruction } = require('../utils/helpers');

/**
 * Visual Authenticity Prompt - Module 1 (Image Authenticity)
 *
 * Instructs Gemini to answer ONLY ONE QUESTION:
 * "Was this image likely captured by an optical camera or generated by an AI model?"
 *
 * CRITICAL RULE: A visually realistic image is NOT automatically authentic.
 * Modern diffusion models (FLUX, Midjourney v6, SDXL, DALL-E 3, Imagen 3) generate
 * photorealistic skin, lighting, hair, and shadows.
 *
 * Returns ONLY: status, confidence, evidence[]
 */
function buildVisualAuthenticityPrompt(metadataInfo, language) {
  const languageInstruction = buildResponseLanguageInstruction(language);
  const styleLanguage = language === 'hi' ? 'natural Hindi (Devanagari script)' : 'plain English';

  return `You are a world-class digital image forensics specialist. Your task is to answer ONLY ONE fundamental question:

"Was this image likely captured by an optical camera in the physical world, or synthesized by an AI generative model / digitally manipulated?"

CRITICAL DETECTION PRINCIPLES — READ CAREFULLY:
1. REALISM IS NOT AUTHENTICITY: Modern AI models (FLUX.1, Midjourney v6, SDXL, DALL-E 3, Imagen 3) routinely generate photorealistic skin, realistic hair, realistic lighting, realistic shadows, and convincing environments. Do NOT assume an image is real simply because it looks realistic or convincing.
2. ORIGIN DETECTION OVER APPEARANCE: Look specifically for physical camera capture signatures vs. AI generative synthesis fingerprints.

HIGH-WEIGHT AI GENERATION INDICATORS — CHECK ALL OF THESE:
- Diffusion rendering artifacts: unnatural micro-smoothing beneath surface noise, plastic or waxy skin sheen
- Synthetic texture patterns: repetitive or unnaturally uniform patterns in fabrics, foliage, hair strands, backgrounds
- Inconsistent object continuity & geometry: impossible architectural perspectives, distorted hands, teeth, buttons, accessories
- AI typography artifacts: gibberish or deformed lettering on signs, shirts, or background elements
- Artificial bokeh & depth-of-field: over-clean subject separation with unnatural edge halos or inconsistent depth blur
- Unrealistic reflections & specular highlights: missing corneal reflection symmetry in eyes, inconsistent light bounce
- Missing genuine optical camera characteristics: absence of physical lens chromatic aberration, absence of true sensor Bayer noise (vs uniform synthetic digital grain)

REDUCED WEIGHT (DO NOT RELY ON THESE ALONE FOR "REAL"):
- Realistic skin, realistic hair, realistic lighting, realistic shadows — these are standard outputs of modern AI models and are NOT sufficient evidence of a real camera photo.

MANIPULATION & DEEPFAKE INDICATORS:
- Deepfake: Face-swap seam artifacts, warping around jawline/hairline, mismatched facial lighting vs neck/torso
- Manipulated: Spliced composite edges, cloning/stamp tool repetition, content-aware fill patches

${languageInstruction}

RESPONSE RULES:
- Output status MUST be exactly one of: "Real", "AI Generated", "Manipulated", "Deepfake", "Uncertain".
- If the image shows signs of AI synthesis or diffusion generation (even if photorealistic), classify as "AI Generated".
- Confidence must be an integer from 0 to 100 representing certainty of origin.
- Evidence MUST be 2 to 4 concise, specific bullet points in ${styleLanguage} describing the exact visual forensic observations (e.g. "Synthetic texture patterns detected in background", "Diffusion rendering artifacts on skin surface", "Unrealistic lighting consistency across subject").
- Do NOT write essays or long summaries.
- Do NOT mention OCR, claims, or text verification.

You MUST respond with ONLY a valid JSON object. No markdown, no code fences, no text outside JSON.

RESPONSE FORMAT:
{
  "status": "Real | AI Generated | Manipulated | Deepfake | Uncertain",
  "confidence": <integer from 0 to 100>,
  "evidence": [
    "<concise evidence bullet 1 in ${styleLanguage}>",
    "<concise evidence bullet 2 in ${styleLanguage}>",
    "<concise evidence bullet 3 in ${styleLanguage}>"
  ]
}`;
}

module.exports = { buildVisualAuthenticityPrompt };
